spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UDEE?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      driverClassName: com.mysql.cj.jdbc.Driver
    database: mysql
    show-sql: true